# Generated by Django 5.2.6 on 2025-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MAKE_CHOICE', 'Выберите департамент'), ('DEPARTMENT_1', '1-й Департамент'), ('DEPARTMENT_2', '2-й Департамент'), ('DEPARTMENT_3', '3-й Департамент'), ('DEPARTMENT_4', '4-й Департамент'), ('DEPARTMENT_5', '5-й Департамент'), ('DEPARTMENT_6', '6-й Департамент')], default='MAKE_CHOICE', verbose_name='Наименование отдела')),
                ('second_name', models.CharField(help_text='Например: Иванов', verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Например: Иван', verbose_name='Имя')),
                ('third_name', models.CharField(help_text='Например: Иванович', verbose_name='Отчество')),
                ('position', models.TextField(verbose_name='Должность')),
                ('phone_number', models.CharField(help_text='8(903)557-55-44', max_length=15, verbose_name='Номер телефона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото')),
                ('e_mail', models.EmailField(help_text='Адрес электронной почты', max_length=254, unique=True)),
                ('hashed_password', models.CharField(default=123456, max_length=128, verbose_name='Пароль')),
                ('password_changed', models.BooleanField(default=False, verbose_name='Новый пароль')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания аккаунта')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Дата последнего изменения аккаунта')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
