# Generated by Django 5.2.6 on 2025-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_alter_employees_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Новый пароль'),
        ),
    ]
