# Generated by Django 5.2.6 on 2025-09-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='library_files/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAuth.employees', verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'Библиотека',
            },
        ),
    ]
